/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as ApiNowpaymentsConfirmRouteImport } from './routes/api/nowpayments/confirm'
import { Route as ApiNowpaymentsInvoiceRouteImport } from './routes/api/nowpayments/invoice'
import { Route as ApiNowpaymentsIpnRouteImport } from './routes/api/nowpayments/ipn'
import { Route as ApiPaddleWebhookRouteImport } from './routes/api/paddle/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNowpaymentsConfirmRoute = ApiNowpaymentsConfirmRouteImport.update({
  id: '/api/nowpayments/confirm',
  path: '/api/nowpayments/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNowpaymentsInvoiceRoute = ApiNowpaymentsInvoiceRouteImport.update({
  id: '/api/nowpayments/invoice',
  path: '/api/nowpayments/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNowpaymentsIpnRoute = ApiNowpaymentsIpnRouteImport.update({
  id: '/api/nowpayments/ipn',
  path: '/api/nowpayments/ipn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaddleWebhookRoute = ApiPaddleWebhookRouteImport.update({
  id: '/api/paddle/webhook',
  path: '/api/paddle/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/nowpayments/confirm': typeof ApiNowpaymentsConfirmRoute
  '/api/nowpayments/invoice': typeof ApiNowpaymentsInvoiceRoute
  '/api/nowpayments/ipn': typeof ApiNowpaymentsIpnRoute
  '/api/paddle/webhook': typeof ApiPaddleWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/nowpayments/confirm': typeof ApiNowpaymentsConfirmRoute
  '/api/nowpayments/invoice': typeof ApiNowpaymentsInvoiceRoute
  '/api/nowpayments/ipn': typeof ApiNowpaymentsIpnRoute
  '/api/paddle/webhook': typeof ApiPaddleWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/nowpayments/confirm': typeof ApiNowpaymentsConfirmRoute
  '/api/nowpayments/invoice': typeof ApiNowpaymentsInvoiceRoute
  '/api/nowpayments/ipn': typeof ApiNowpaymentsIpnRoute
  '/api/paddle/webhook': typeof ApiPaddleWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/checkout/success'
    | '/api/nowpayments/confirm'
    | '/api/nowpayments/invoice'
    | '/api/nowpayments/ipn'
    | '/api/paddle/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/checkout/success'
    | '/api/nowpayments/confirm'
    | '/api/nowpayments/invoice'
    | '/api/nowpayments/ipn'
    | '/api/paddle/webhook'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/checkout/success'
    | '/api/nowpayments/confirm'
    | '/api/nowpayments/invoice'
    | '/api/nowpayments/ipn'
    | '/api/paddle/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ApiNowpaymentsConfirmRoute: typeof ApiNowpaymentsConfirmRoute
  ApiNowpaymentsInvoiceRoute: typeof ApiNowpaymentsInvoiceRoute
  ApiNowpaymentsIpnRoute: typeof ApiNowpaymentsIpnRoute
  ApiPaddleWebhookRoute: typeof ApiPaddleWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nowpayments/confirm': {
      id: '/api/nowpayments/confirm'
      path: '/api/nowpayments/confirm'
      fullPath: '/api/nowpayments/confirm'
      preLoaderRoute: typeof ApiNowpaymentsConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nowpayments/invoice': {
      id: '/api/nowpayments/invoice'
      path: '/api/nowpayments/invoice'
      fullPath: '/api/nowpayments/invoice'
      preLoaderRoute: typeof ApiNowpaymentsInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nowpayments/ipn': {
      id: '/api/nowpayments/ipn'
      path: '/api/nowpayments/ipn'
      fullPath: '/api/nowpayments/ipn'
      preLoaderRoute: typeof ApiNowpaymentsIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paddle/webhook': {
      id: '/api/paddle/webhook'
      path: '/api/paddle/webhook'
      fullPath: '/api/paddle/webhook'
      preLoaderRoute: typeof ApiPaddleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ApiNowpaymentsConfirmRoute: ApiNowpaymentsConfirmRoute,
  ApiNowpaymentsInvoiceRoute: ApiNowpaymentsInvoiceRoute,
  ApiNowpaymentsIpnRoute: ApiNowpaymentsIpnRoute,
  ApiPaddleWebhookRoute: ApiPaddleWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
